In [1]:
# 라이브러리 할당
import pandas as pd
import json
import numpy as np

In [2]:
# 파일 불러오기
file_path = "enwiki_raw_log.txt"
df = pd.read_json(file_path, lines=True)

In [3]:
# 데이터 구조 확인
print("--- 데이터 상단 5행 ---")
print(df.head())

print("\n--- 전체 컬럼 목록 ---")
print(df.columns)

--- 데이터 상단 5행 ---
                         $schema  \
0  /mediawiki/recentchange/1.0.0
1  /mediawiki/recentchange/1.0.0
2  /mediawiki/recentchange/1.0.0
3  /mediawiki/recentchange/1.0.0
4  /mediawiki/recentchange/1.0.0

                                                meta            id  \
0  {'uri': 'https://en.wikipedia.org/wiki/Killing...  2.006462e+09
1  {'uri': 'https://en.wikipedia.org/wiki/Categor...  2.006462e+09
2  {'uri': 'https://en.wikipedia.org/wiki/Party_o...  2.006462e+09
3  {'uri': 'https://en.wikipedia.org/wiki/Macedon...  2.006462e+09
4  {'uri': 'https://en.wikipedia.org/wiki/Battle_...  2.006462e+09

         type  namespace                                         title  \
0        edit          0                    Killing of Natalie McNally
1  categorize         14         Category:Political parties in Albania
2        edit          0                Party of the Vlachs of Albania
3        edit          0  Macedonian Alliance for European Integration
4        edit          0                       Battle of Sutlej (1765)

                                           title_url  \
0  https://en.wikipedia.org/wiki/Killing_of_Natal...
1  https://en.wikipedia.org/wiki/Category:Politic...
2  https://en.wikipedia.org/wiki/Party_of_the_Vla...
3  https://en.wikipedia.org/wiki/Macedonian_Allia...
4  https://en.wikipedia.org/wiki/Battle_of_Sutlej...

                                             comment           timestamp  \
0               /* Defence submissions */ fixed typo 2026-03-16 16:16:38
1  [[:Libra Party]] removed from category, [[Spec... 2026-03-16 16:16:35
2  Removing from [[Category:Political parties in ... 2026-03-16 16:16:37
3  Removing from [[Category:Political parties in ... 2026-03-16 16:16:36
4                                                    2026-03-16 16:16:38

                         user  ...       server_name server_script_path  \
0  WorldTravleerAndPhotoTaker  ...  en.wikipedia.org                 /w
1      Ser Amantio di Nicolao  ...  en.wikipedia.org                 /w
2      Ser Amantio di Nicolao  ...  en.wikipedia.org                 /w
3      Ser Amantio di Nicolao  ...  en.wikipedia.org                 /w
4              ~2026-16707-59  ...  en.wikipedia.org                 /w

     wiki                                      parsedcomment patrolled log_id  \
0  enwiki  <span class="autocomment"><a href="/wiki/Killi...       NaN    NaN
1  enwiki  <a href="/wiki/Libra_Party" title="Libra Party...       NaN    NaN
2  enwiki  Removing from <a href="/wiki/Category:Politica...       NaN    NaN
3  enwiki  Removing from <a href="/wiki/Category:Politica...       NaN    NaN
4  enwiki                                                          NaN    NaN

  log_type log_action log_params log_action_comment
0      NaN        NaN        NaN                NaN
1      NaN        NaN        NaN                NaN
2      NaN        NaN        NaN                NaN
3      NaN        NaN        NaN                NaN
4      NaN        NaN        NaN                NaN

[5 rows x 26 columns]

--- 전체 컬럼 목록 ---
Index(['$schema', 'meta', 'id', 'type', 'namespace', 'title', 'title_url',
       'comment', 'timestamp', 'user', 'bot', 'notify_url', 'minor', 'length',
       'revision', 'server_url', 'server_name', 'server_script_path', 'wiki',
       'parsedcomment', 'patrolled', 'log_id', 'log_type', 'log_action',
       'log_params', 'log_action_comment'],
      dtype='object')

In [4]:
# 컬럼별 결측치 확인
print(df.isnull().sum())

$schema                  0
meta                     0
id                     168
type                     0
namespace                0
title                    0
title_url                0
comment                  0
timestamp                0
user                     0
bot                      0
notify_url             290
minor                 1336
length                1336
revision              1336
server_url               0
server_name              0
server_script_path       0
wiki                     0
parsedcomment            0
patrolled             3319
log_id                3104
log_type              3104
log_action            3104
log_params            3104
log_action_comment    3104
dtype: int64

In [5]:
# 결측치 비율(%) 확인 
print((df.isnull().sum() / len(df)) * 100)

$schema                0.000000
meta                   0.000000
id                     4.949912
type                   0.000000
namespace              0.000000
title                  0.000000
title_url              0.000000
comment                0.000000
timestamp              0.000000
user                   0.000000
bot                    0.000000
notify_url             8.544490
minor                 39.363583
length                39.363583
revision              39.363583
server_url             0.000000
server_name            0.000000
server_script_path     0.000000
wiki                   0.000000
parsedcomment          0.000000
patrolled             97.790218
log_id                91.455510
log_type              91.455510
log_action            91.455510
log_params            91.455510
log_action_comment    91.455510
dtype: float64

In [6]:
# 결측치 90%가 넘는 컬럼 삭제
df = df.drop(columns=['patrolled','log_id','log_type',
                      'log_action','log_params','log_action_comment'])

In [7]:
df

,$schema,meta,id,type,namespace,title,title_url,comment,timestamp,user,bot,notify_url,minor,length,revision,server_url,server_name,server_script_path,wiki,parsedcomment
0,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Killing...,2.006462e+09,edit,0,Killing of Natalie McNally,https://en.wikipedia.org/wiki/Killing_of_Natal...,/* Defence submissions */ fixed typo,2026-03-16 16:16:38,WorldTravleerAndPhotoTaker,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 33933, 'new': 33932}","{'old': 1343821096, 'new': 1343821145}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Killi..."
1,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Categor...,2.006462e+09,categorize,14,Category:Political parties in Albania,https://en.wikipedia.org/wiki/Category:Politic...,"[[:Libra Party]] removed from category, [[Spec...",2026-03-16 16:16:35,Ser Amantio di Nicolao,False,https://en.wikipedia.org/w/index.php?diff=1343...,NaN,NaN,NaN,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<a href=""/wiki/Libra_Party"" title=""Libra Party..."
2,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Party_o...,2.006462e+09,edit,0,Party of the Vlachs of Albania,https://en.wikipedia.org/wiki/Party_of_the_Vla...,Removing from [[Category:Political parties in ...,2026-03-16 16:16:37,Ser Amantio di Nicolao,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 7219, 'new': 7177}","{'old': 1305255087, 'new': 1343821147}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"Removing from <a href=""/wiki/Category:Politica..."
3,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Macedon...,2.006462e+09,edit,0,Macedonian Alliance for European Integration,https://en.wikipedia.org/wiki/Macedonian_Allia...,Removing from [[Category:Political parties in ...,2026-03-16 16:16:36,Ser Amantio di Nicolao,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 14630, 'new': 14588}","{'old': 1301952821, 'new': 1343821141}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"Removing from <a href=""/wiki/Category:Politica..."
4,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Battle_...,2.006462e+09,edit,0,Battle of Sutlej (1765),https://en.wikipedia.org/wiki/Battle_of_Sutlej...,,2026-03-16 16:16:38,~2026-16707-59,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 12258, 'new': 12270}","{'old': 1343793152, 'new': 1343821149}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3389,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/User:Ve...,2.006466e+09,edit,2,User:Vector2019/Non-fiction books about nuclea...,https://en.wikipedia.org/wiki/User:Vector2019/...,Undid revision [[Special:Diff/1343823179|13438...,2026-03-16 16:32:41,Vector2019,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 16038, 'new': 16037}","{'old': 1343823179, 'new': 1343823326}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"Undid revision <a href=""/wiki/Special:Diff/134..."
3390,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Categor...,2.006466e+09,categorize,14,Category:Women war correspondents of the Russo...,https://en.wikipedia.org/wiki/Category:Women_w...,"[[:Iva Sidash]] added to category, [[Special:W...",2026-03-16 16:32:39,ForsythiaJo,False,https://en.wikipedia.org/w/index.php?diff=1343...,NaN,NaN,NaN,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<a href=""/wiki/Iva_Sidash"" title=""Iva Sidash"">..."
3391,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Montros...,2.006466e+09,edit,0,Montrose F.C.,https://en.wikipedia.org/wiki/Montrose_F.C.,/* Other notable players */,2026-03-16 16:32:40,Gudlator,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 40198, 'new': 40069}","{'old': 1343820002, 'new': 1343823321}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Montr..."
3392,/mediawiki/recentchange/1.0.0,"{'uri': 'https://en.wikipedia.org/wiki/KGBN', ...",2.006466e+09,edit,0,KGBN,https://en.wikipedia.org/wiki/KGBN,"added [[Category:Religion in Orange County, Ca...",2026-03-16 16:32:42,RevelationDirect,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 8714, 'new': 8765}","{'old': 1343823192, 'new': 1343823330}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"added <a href=""/wiki/Category:Religion_in_Oran..."
3393,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Blowup'...,2.006466e+09,edit,0,Blowup,https://en.wikipedia.org/wiki/Blowup,/* Cast */ ref models,2026-03-16 16:32:41,Thincat,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 45155, 'new': 45526}","{'old': 1343821395, 'new': 1343823327}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Blowu..."

In [8]:
# meta 컬럼 삭제
df = df.drop(columns=['meta'])

In [9]:
df

,$schema,id,type,namespace,title,title_url,comment,timestamp,user,bot,notify_url,minor,length,revision,server_url,server_name,server_script_path,wiki,parsedcomment
0,/mediawiki/recentchange/1.0.0,2.006462e+09,edit,0,Killing of Natalie McNally,https://en.wikipedia.org/wiki/Killing_of_Natal...,/* Defence submissions */ fixed typo,2026-03-16 16:16:38,WorldTravleerAndPhotoTaker,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 33933, 'new': 33932}","{'old': 1343821096, 'new': 1343821145}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Killi..."
1,/mediawiki/recentchange/1.0.0,2.006462e+09,categorize,14,Category:Political parties in Albania,https://en.wikipedia.org/wiki/Category:Politic...,"[[:Libra Party]] removed from category, [[Spec...",2026-03-16 16:16:35,Ser Amantio di Nicolao,False,https://en.wikipedia.org/w/index.php?diff=1343...,NaN,NaN,NaN,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<a href=""/wiki/Libra_Party"" title=""Libra Party..."
2,/mediawiki/recentchange/1.0.0,2.006462e+09,edit,0,Party of the Vlachs of Albania,https://en.wikipedia.org/wiki/Party_of_the_Vla...,Removing from [[Category:Political parties in ...,2026-03-16 16:16:37,Ser Amantio di Nicolao,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 7219, 'new': 7177}","{'old': 1305255087, 'new': 1343821147}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"Removing from <a href=""/wiki/Category:Politica..."
3,/mediawiki/recentchange/1.0.0,2.006462e+09,edit,0,Macedonian Alliance for European Integration,https://en.wikipedia.org/wiki/Macedonian_Allia...,Removing from [[Category:Political parties in ...,2026-03-16 16:16:36,Ser Amantio di Nicolao,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 14630, 'new': 14588}","{'old': 1301952821, 'new': 1343821141}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"Removing from <a href=""/wiki/Category:Politica..."
4,/mediawiki/recentchange/1.0.0,2.006462e+09,edit,0,Battle of Sutlej (1765),https://en.wikipedia.org/wiki/Battle_of_Sutlej...,,2026-03-16 16:16:38,~2026-16707-59,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 12258, 'new': 12270}","{'old': 1343793152, 'new': 1343821149}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3389,/mediawiki/recentchange/1.0.0,2.006466e+09,edit,2,User:Vector2019/Non-fiction books about nuclea...,https://en.wikipedia.org/wiki/User:Vector2019/...,Undid revision [[Special:Diff/1343823179|13438...,2026-03-16 16:32:41,Vector2019,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 16038, 'new': 16037}","{'old': 1343823179, 'new': 1343823326}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"Undid revision <a href=""/wiki/Special:Diff/134..."
3390,/mediawiki/recentchange/1.0.0,2.006466e+09,categorize,14,Category:Women war correspondents of the Russo...,https://en.wikipedia.org/wiki/Category:Women_w...,"[[:Iva Sidash]] added to category, [[Special:W...",2026-03-16 16:32:39,ForsythiaJo,False,https://en.wikipedia.org/w/index.php?diff=1343...,NaN,NaN,NaN,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<a href=""/wiki/Iva_Sidash"" title=""Iva Sidash"">..."
3391,/mediawiki/recentchange/1.0.0,2.006466e+09,edit,0,Montrose F.C.,https://en.wikipedia.org/wiki/Montrose_F.C.,/* Other notable players */,2026-03-16 16:32:40,Gudlator,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 40198, 'new': 40069}","{'old': 1343820002, 'new': 1343823321}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Montr..."
3392,/mediawiki/recentchange/1.0.0,2.006466e+09,edit,0,KGBN,https://en.wikipedia.org/wiki/KGBN,"added [[Category:Religion in Orange County, Ca...",2026-03-16 16:32:42,RevelationDirect,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 8714, 'new': 8765}","{'old': 1343823192, 'new': 1343823330}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"added <a href=""/wiki/Category:Religion_in_Oran..."
3393,/mediawiki/recentchange/1.0.0,2.006466e+09,edit,0,Blowup,https://en.wikipedia.org/wiki/Blowup,/* Cast */ ref models,2026-03-16 16:32:41,Thincat,False,https://en.wikipedia.org/w/index.php?diff=1343...,0.0,"{'old': 45155, 'new': 45526}","{'old': 1343821395, 'new': 1343823327}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Blowu..."

In [10]:
# length의 결측값은 old와 new 다 0으로 채우기 
# why? 결과적으로 내용의 길이가 바뀌지 않았다는 의미이기 떄문이다

# length를 length_old와 length_new로 컬럼 불리하기
def split_length(row):
    if isinstance(row,dict):
        return pd.Series([row.get('old',0), row.get('new',0)])
    # NAN이면 0으로 채움
    else:
        return pd.Series([0,0])

# length 컬럼 적용하여 새로운 두 컬럼 생성
df[['length_old', 'length_new']] = df['length'].apply(split_length)

# 불리된 후에도 결측치 남을 것을 대비해 0으로 채우기
df['length_old'] = df['length_old'].fillna(0).astype(int)
df['length_new'] = df['length_new'].fillna(0).astype(int)

# len_diff 계산하기
df['len_diff'] = df['length_new'] - df['length_old']

print('length컬럼 처리 완료')

length컬럼 처리 완료

In [11]:
df

,$schema,id,type,namespace,title,title_url,comment,timestamp,user,bot,...,length,revision,server_url,server_name,server_script_path,wiki,parsedcomment,length_old,length_new,len_diff
0,/mediawiki/recentchange/1.0.0,2.006462e+09,edit,0,Killing of Natalie McNally,https://en.wikipedia.org/wiki/Killing_of_Natal...,/* Defence submissions */ fixed typo,2026-03-16 16:16:38,WorldTravleerAndPhotoTaker,False,...,"{'old': 33933, 'new': 33932}","{'old': 1343821096, 'new': 1343821145}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Killi...",33933,33932,-1
1,/mediawiki/recentchange/1.0.0,2.006462e+09,categorize,14,Category:Political parties in Albania,https://en.wikipedia.org/wiki/Category:Politic...,"[[:Libra Party]] removed from category, [[Spec...",2026-03-16 16:16:35,Ser Amantio di Nicolao,False,...,NaN,NaN,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<a href=""/wiki/Libra_Party"" title=""Libra Party...",0,0,0
2,/mediawiki/recentchange/1.0.0,2.006462e+09,edit,0,Party of the Vlachs of Albania,https://en.wikipedia.org/wiki/Party_of_the_Vla...,Removing from [[Category:Political parties in ...,2026-03-16 16:16:37,Ser Amantio di Nicolao,False,...,"{'old': 7219, 'new': 7177}","{'old': 1305255087, 'new': 1343821147}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"Removing from <a href=""/wiki/Category:Politica...",7219,7177,-42
3,/mediawiki/recentchange/1.0.0,2.006462e+09,edit,0,Macedonian Alliance for European Integration,https://en.wikipedia.org/wiki/Macedonian_Allia...,Removing from [[Category:Political parties in ...,2026-03-16 16:16:36,Ser Amantio di Nicolao,False,...,"{'old': 14630, 'new': 14588}","{'old': 1301952821, 'new': 1343821141}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"Removing from <a href=""/wiki/Category:Politica...",14630,14588,-42
4,/mediawiki/recentchange/1.0.0,2.006462e+09,edit,0,Battle of Sutlej (1765),https://en.wikipedia.org/wiki/Battle_of_Sutlej...,,2026-03-16 16:16:38,~2026-16707-59,False,...,"{'old': 12258, 'new': 12270}","{'old': 1343793152, 'new': 1343821149}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,,12258,12270,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3389,/mediawiki/recentchange/1.0.0,2.006466e+09,edit,2,User:Vector2019/Non-fiction books about nuclea...,https://en.wikipedia.org/wiki/User:Vector2019/...,Undid revision [[Special:Diff/1343823179|13438...,2026-03-16 16:32:41,Vector2019,False,...,"{'old': 16038, 'new': 16037}","{'old': 1343823179, 'new': 1343823326}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"Undid revision <a href=""/wiki/Special:Diff/134...",16038,16037,-1
3390,/mediawiki/recentchange/1.0.0,2.006466e+09,categorize,14,Category:Women war correspondents of the Russo...,https://en.wikipedia.org/wiki/Category:Women_w...,"[[:Iva Sidash]] added to category, [[Special:W...",2026-03-16 16:32:39,ForsythiaJo,False,...,NaN,NaN,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<a href=""/wiki/Iva_Sidash"" title=""Iva Sidash"">...",0,0,0
3391,/mediawiki/recentchange/1.0.0,2.006466e+09,edit,0,Montrose F.C.,https://en.wikipedia.org/wiki/Montrose_F.C.,/* Other notable players */,2026-03-16 16:32:40,Gudlator,False,...,"{'old': 40198, 'new': 40069}","{'old': 1343820002, 'new': 1343823321}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Montr...",40198,40069,-129
3392,/mediawiki/recentchange/1.0.0,2.006466e+09,edit,0,KGBN,https://en.wikipedia.org/wiki/KGBN,"added [[Category:Religion in Orange County, Ca...",2026-03-16 16:32:42,RevelationDirect,False,...,"{'old': 8714, 'new': 8765}","{'old': 1343823192, 'new': 1343823330}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"added <a href=""/wiki/Category:Religion_in_Oran...",8714,8765,51
3393,/mediawiki/recentchange/1.0.0,2.006466e+09,edit,0,Blowup,https://en.wikipedia.org/wiki/Blowup,/* Cast */ ref models,2026-03-16 16:32:41,Thincat,False,...,"{'old': 45155, 'new': 45526}","{'old': 1343821395, 'new': 1343823327}",https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Blowu...",45155,45526,371

In [12]:
# length 컬럼 삭제
df = df.drop(columns=['length'])

In [13]:
df.columns

Index(['$schema', 'id', 'type', 'namespace', 'title', 'title_url', 'comment',
       'timestamp', 'user', 'bot', 'notify_url', 'minor', 'revision',
       'server_url', 'server_name', 'server_script_path', 'wiki',
       'parsedcomment', 'length_old', 'length_new', 'len_diff'],
      dtype='object')

In [14]:
# $schema의 value counts
print(df['$schema'].value_counts())

$schema
/mediawiki/recentchange/1.0.0    3394
Name: count, dtype: int64

In [15]:
# $schema 열 삭제
df = df.drop(columns=['$schema'])

In [16]:
df.columns

Index(['id', 'type', 'namespace', 'title', 'title_url', 'comment', 'timestamp',
       'user', 'bot', 'notify_url', 'minor', 'revision', 'server_url',
       'server_name', 'server_script_path', 'wiki', 'parsedcomment',
       'length_old', 'length_new', 'len_diff'],
      dtype='object')

In [17]:
# 시간 간격 계산 time_delta

# timestamp 컬럼을 초 단위 숫자에서 '날짜/시간' 형식으로 변환
df['timestamp'] = pd.to_datetime(df['timestamp'], unit='s')

# 데이터를 '문서 제목'별로 묶고, 그 안에서 '시간순'으로 정렬
df = df.sort_values(by=['title', 'timestamp'])

# 문서별(title)로 그룹을 지어 직전 행과의 시간 차이 계산
df['time_delta'] = df.groupby('title')['timestamp'].diff()

# 시간 차이를 '초(seconds)' 단위의 숫자로 변환
df['time_delta_sec'] = df['time_delta'].dt.total_seconds()

# 첫 편집은 직전 기록이 없어서 NaN(결측치)이 생기므로 0으로 채워줍니다.
df['time_delta_sec'] = df['time_delta_sec'].fillna(0)

# 결과 확인
print("✅ 시간 간격 계산 완료!")
print(df[['title', 'timestamp', 'time_delta_sec']].head(10))

✅ 시간 간격 계산 완료!
                                    title           timestamp  time_delta_sec
768                                     0 2026-03-16 16:20:08             0.0
1184                       112th Grey Cup 2026-03-16 16:22:13             0.0
1402       13th Illinois General Assembly 2026-03-16 16:23:28             0.0
1452  13th Parliament of British Columbia 2026-03-16 16:23:42             0.0
1440                13th Tripura Assembly 2026-03-16 16:23:39             0.0
2195                13th Tripura Assembly 2026-03-16 16:27:19           220.0
2379                13th Tripura Assembly 2026-03-16 16:28:12            53.0
2556                13th Tripura Assembly 2026-03-16 16:29:00            48.0
1546       17th Illinois General Assembly 2026-03-16 16:24:07             0.0
1632   1889 Newfoundland general election 2026-03-16 16:24:45             0.0

In [18]:
df.head(10)

,id,type,namespace,title,title_url,comment,timestamp,user,bot,notify_url,...,server_url,server_name,server_script_path,wiki,parsedcomment,length_old,length_new,len_diff,time_delta,time_delta_sec
768,2.006463e+09,edit,0,0,https://en.wikipedia.org/wiki/0,/* India */ Fix unnecessary capitalization,2026-03-16 16:20:08,Finalthunder526,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/0#Ind...",77336,77336,0,NaT,0.0
1184,2.006464e+09,edit,0,112th Grey Cup,https://en.wikipedia.org/wiki/112th_Grey_Cup,v2.05 - Repaired 1 link to disambiguation page...,2026-03-16 16:22:13,Tassedethe,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,v2.05 - Repaired 1 link to disambiguation page...,52533,52566,33,NaT,0.0
1402,2.006464e+09,edit,0,13th Illinois General Assembly,https://en.wikipedia.org/wiki/13th_Illinois_Ge...,"/* House */ Typo fixing, replaced: politican →...",2026-03-16 16:23:28,John of Reading,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/13th_...",24570,24571,1,NaT,0.0
1452,2.006464e+09,edit,0,13th Parliament of British Columbia,https://en.wikipedia.org/wiki/13th_Parliament_...,"/* top */ Typo fixing, replaced: polititian → ...",2026-03-16 16:23:42,John of Reading,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/13th_...",12690,12690,0,NaT,0.0
1440,2.006464e+09,edit,0,13th Tripura Assembly,https://en.wikipedia.org/wiki/13th_Tripura_Ass...,/* Members of Legislative Assembly */,2026-03-16 16:23:39,~2026-13797-11,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/13th_...",19183,19427,244,NaT,0.0
2195,2.006465e+09,edit,0,13th Tripura Assembly,https://en.wikipedia.org/wiki/13th_Tripura_Ass...,/* Members of Legislative Assembly */,2026-03-16 16:27:19,~2026-13797-11,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/13th_...",19427,19454,27,0 days 00:03:40,220.0
2379,2.006465e+09,edit,0,13th Tripura Assembly,https://en.wikipedia.org/wiki/13th_Tripura_Ass...,/* Members of Legislative Assembly */,2026-03-16 16:28:12,~2026-13797-11,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/13th_...",19454,19454,0,0 days 00:00:53,53.0
2556,2.006465e+09,edit,0,13th Tripura Assembly,https://en.wikipedia.org/wiki/13th_Tripura_Ass...,/* Members of Legislative Assembly */,2026-03-16 16:29:00,~2026-13797-11,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/13th_...",19454,19518,64,0 days 00:00:48,48.0
1546,2.006464e+09,edit,0,17th Illinois General Assembly,https://en.wikipedia.org/wiki/17th_Illinois_Ge...,"/* House */ Typo fixing, replaced: politican →...",2026-03-16 16:24:07,John of Reading,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/17th_...",11657,11658,1,NaT,0.0
1632,2.006464e+09,edit,0,1889 Newfoundland general election,https://en.wikipedia.org/wiki/1889_Newfoundlan...,"/* Eastern Newfoundland */ Typo fixing, replac...",2026-03-16 16:24:45,John of Reading,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/1889_...",19298,19299,1,NaT,0.0

In [19]:
df.columns

Index(['id', 'type', 'namespace', 'title', 'title_url', 'comment', 'timestamp',
       'user', 'bot', 'notify_url', 'minor', 'revision', 'server_url',
       'server_name', 'server_script_path', 'wiki', 'parsedcomment',
       'length_old', 'length_new', 'len_diff', 'time_delta', 'time_delta_sec'],
      dtype='object')

In [21]:
print("user 컬럼 확인")
print(df['user'].value_counts())
print("\n")
print("\n")
print("bot 컬럼 확인")
print(df['bot'].value_counts())

user 컬럼 확인
user
Lollipoplollipoplollipop    172
ForsythiaJo                  93
BlackJack                    85
Tarkowski                    65
Tassedethe                   51
                           ...
Townboyeditor                 1
Dev Adhi                      1
Mikikooo                      1
Thugwood                      1
Archon 2488                   1
Name: count, Length: 820, dtype: int64




bot 컬럼 확인
bot
False    3211
True      183
Name: count, dtype: int64

In [22]:
print("user 컬럼 내림차순 확인")
print(df['user'].value_counts().sort_values(ascending=False).head(15))

user 컬럼 내림차순 확인
user
Lollipoplollipoplollipop    172
ForsythiaJo                  93
BlackJack                    85
Tarkowski                    65
Tassedethe                   51
Victuallers                  49
Liz                          47
Primefac                     40
Ser Amantio di Nicolao       38
AnomieBOT                    37
Donnowin1                    34
UserNumber                   33
Waxworker                    29
John of Reading              28
Enbi                         28
Name: count, dtype: int64

In [26]:
print(df.isnull().sum())

id                     168
type                     0
namespace                0
title                    0
title_url                0
comment                  0
timestamp                0
user                     0
bot                      0
notify_url             290
minor                 1336
revision              1336
server_url               0
server_name              0
server_script_path       0
wiki                     0
parsedcomment            0
length_old               0
length_new               0
len_diff                 0
time_delta            2180
time_delta_sec           0
dtype: int64

In [46]:
# 결측치 비율(%) 확인 
print((df.isnull().sum() / len(df)) * 100)

id                     4.949912
type                   0.000000
namespace              0.000000
title                  0.000000
title_url              0.000000
comment                0.000000
timestamp              0.000000
user                   0.000000
bot                    0.000000
notify_url             8.544490
minor                 39.363583
revision              39.363583
server_url             0.000000
server_name            0.000000
server_script_path     0.000000
wiki                   0.000000
parsedcomment          0.000000
length_old             0.000000
length_new             0.000000
len_diff               0.000000
time_delta            64.230996
time_delta_sec         0.000000
dtype: float64

In [50]:
# minor nan 편집
# 체크박스 선택인데 선택을 안했다 = 일반 편집이다
df['minor'] = df['minor'].fillna(False)

In [54]:
# revision nan 처리
# 버전 정보가 없다는 건 지식의 누적 기록이 없는 상태를 위미
df['revision'] = df['revision'].fillna(0)

In [56]:
print(df.isnull().sum())

id                     168
type                     0
namespace                0
title                    0
title_url                0
comment                  0
timestamp                0
user                     0
bot                      0
notify_url             290
minor                    0
revision                 0
server_url               0
server_name              0
server_script_path       0
wiki                     0
parsedcomment            0
length_old               0
length_new               0
len_diff                 0
time_delta            2180
time_delta_sec           0
dtype: int64

In [60]:
# id의 경우 DB table에서 pk로 쓰여야함으로 살려둠 (ML에는 사용 X)
df = df.dropna(subset=['id'])

In [62]:
df

,id,type,namespace,title,title_url,comment,timestamp,user,bot,notify_url,...,server_url,server_name,server_script_path,wiki,parsedcomment,length_old,length_new,len_diff,time_delta,time_delta_sec
768,2.006463e+09,edit,0,0,https://en.wikipedia.org/wiki/0,/* India */ Fix unnecessary capitalization,2026-03-16 16:20:08,Finalthunder526,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/0#Ind...",77336,77336,0,NaT,0.0
1184,2.006464e+09,edit,0,112th Grey Cup,https://en.wikipedia.org/wiki/112th_Grey_Cup,v2.05 - Repaired 1 link to disambiguation page...,2026-03-16 16:22:13,Tassedethe,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,v2.05 - Repaired 1 link to disambiguation page...,52533,52566,33,NaT,0.0
1402,2.006464e+09,edit,0,13th Illinois General Assembly,https://en.wikipedia.org/wiki/13th_Illinois_Ge...,"/* House */ Typo fixing, replaced: politican →...",2026-03-16 16:23:28,John of Reading,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/13th_...",24570,24571,1,NaT,0.0
1452,2.006464e+09,edit,0,13th Parliament of British Columbia,https://en.wikipedia.org/wiki/13th_Parliament_...,"/* top */ Typo fixing, replaced: polititian → ...",2026-03-16 16:23:42,John of Reading,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/13th_...",12690,12690,0,NaT,0.0
1440,2.006464e+09,edit,0,13th Tripura Assembly,https://en.wikipedia.org/wiki/13th_Tripura_Ass...,/* Members of Legislative Assembly */,2026-03-16 16:23:39,~2026-13797-11,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/13th_...",19183,19427,244,NaT,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048,2.006464e+09,edit,0,Zee Asadel,https://en.wikipedia.org/wiki/Zee_Asadel,/* Film */,2026-03-16 16:21:40,~2026-16376-68,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,"<span class=""autocomment""><a href=""/wiki/Zee_A...",19958,20203,245,NaT,0.0
590,2.006463e+09,edit,0,Zenande Mfenyana,https://en.wikipedia.org/wiki/Zenande_Mfenyana,Expanding article,2026-03-16 16:19:12,Colanao Khod,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,Expanding article,4988,5470,482,NaT,0.0
1819,2.006464e+09,edit,0,Zhang Dingfan,https://en.wikipedia.org/wiki/Zhang_Dingfan,Dating maintenance tags: {{More citations}},2026-03-16 16:25:35,AnomieBOT,True,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,Dating maintenance tags: {{More citations}},5915,5931,16,NaT,0.0
2993,2.006466e+09,edit,0,Étienne-Charles de Damas-Crux,https://en.wikipedia.org/wiki/%C3%89tienne-Cha...,Dating maintenance tags: {{Cn}} {{More citatio...,2026-03-16 16:31:03,AnomieBOT,True,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,Dating maintenance tags: {{Cn}} {{More citatio...,8310,8342,32,NaT,0.0
69,2.006462e+09,edit,0,Škoda Works,https://en.wikipedia.org/wiki/%C5%A0koda_Works,en dash,2026-03-16 16:16:54,Archon 2488,False,https://en.wikipedia.org/w/index.php?diff=1343...,...,https://en.wikipedia.org,en.wikipedia.org,/w,enwiki,en dash,24797,24806,9,NaT,0.0

In [64]:
df.shape

(3226, 22)

In [66]:
# 확실히 필요 없는 열들 리스트
# notify_url을 포함하여 서버 정보 등 분석에 불필요한 것들을 모았습니다.
cols_to_drop = ['notify_url', 'server_name', 'server_script_path', 'server_url', 'title_url']

# 리스트에 있는 컬럼 중 실제로 데이터프레임에 존재하는 것만 골라 삭제
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

print("✅ notify_url 및 불필요한 컬럼 삭제 완료!")
print(f"현재 남은 컬럼: {list(df.columns)}")

✅ notify_url 및 불필요한 컬럼 삭제 완료!
현재 남은 컬럼: ['id', 'type', 'namespace', 'title', 'comment', 'timestamp', 'user', 'bot', 'minor', 'revision', 'wiki', 'parsedcomment', 'length_old', 'length_new', 'len_diff', 'time_delta', 'time_delta_sec']

In [68]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 3226 entries, 768 to 69
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              3226 non-null   float64
 1   type            3226 non-null   object
 2   namespace       3226 non-null   int64
 3   title           3226 non-null   object
 4   comment         3226 non-null   object
 5   timestamp       3226 non-null   datetime64[ns]
 6   user            3226 non-null   object
 7   bot             3226 non-null   bool
 8   minor           3226 non-null   object
 9   revision        3226 non-null   object
 10  wiki            3226 non-null   object
 11  parsedcomment   3226 non-null   object
 12  length_old      3226 non-null   int32
 13  length_new      3226 non-null   int32
 14  len_diff        3226 non-null   int32
 15  time_delta      1084 non-null   timedelta64[ns]
 16  time_delta_sec  3226 non-null   float64
dtypes: bool(1), datetime64[ns](1), float64(2), int32(3), int64(1), object(8), timedelta64[ns](1)
memory usage: 393.8+ KB
None

In [70]:
df.to_csv('wiki_trend.csv', index=False, encoding='utf-8')